### PR TITLE
scotus: Supreme Court conversation data

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Comment by julien-c** [comment]
@Conchylicultor @eschnou I think it would be very handy to just pass a flag to import a dataset of similarly-formatted data (e.g. either one very long conversation like here, or a lightweight format that would just separate linear conversations between 2 people)

What do you think?

**Comment by julien-c** [comment]
Example format:
```
from A to B
from B to A
from A to B
from B to A
from A to B
===
from C to D
from D to C
from C to D
from D to C
from C to D
from D to C
...
```

**Comment by eschnou** [comment]
I really like the idea, which will make it easier to have a large collection of various datasets, without having to keep adding special cases to textdata.py.

**Comment by Conchylicultor** [comment]
I modified `textdata.py` in order to simplify the addition of new datasets.
Now only [one line](https://github.com/Conchylicultor/DeepQA/blob/master/chatbot/textdata.py#L50) should be modified to registered a new corpus.

In any case, even if a new custom DeepQA format is added, we still need a script to convert the existing datasets to that format, which is basically the same that adding a new `*data.py` to DeepQA. The potential advantage I see for using a custom format would be:
* More human readable
* Probably smaller file size
* Could be used to easily merge datasets together

**Pull request merged**
