### PR TITLE
Migration work to TF v0.12.0

### PR DESCRIPTION
**Pull request by zameran**
Variables initialization method is deprecated.
So, fixed, to get it more clear.

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thank you for your contribution. Indeed, there have been some change in the API with the last version. The 0.12 is just a release candidate so is fairly recent.
I can't merge the pull request currently because it will break the program for most people which are still using 0.11 or 0.10.

**Comment by zameran** [comment]
Ok. But take it in to account in the future. Thx!

**Comment by zameran** [comment]
I fix some summary. Anyway, i think there are a lot of stuff should be fixed to work good on TF 0.12 release.
Cheers!

**Comment by Conchylicultor** [comment]
I created a new experimental branch `tf_0_12` to push the API changes of TensorFlow 0.12. To use it, just switch to that branch:

```
git checkout tf_0_12
```

**Pull request merged**
